language: python
python:
  - "3.5"
  - "3.6-dev"
install: 
  - pip install -r requirements-dev.txt
  - pip install .
script:
  - pytest
  - coverage run --source craigslist -m pytest
after_success:
  - coveralls
