language: python
python:
  - "3.5"
  - "3.6-dev"
install: 
  - pip install .
  - pip install -r requirements-dev.txt
script:
  - pytest
  - coverage run --source craigslist --omit craigslist._search.jsonsearch.async,craigslist.api.async -m pytest
after_success:
  - coveralls
