language: python
python:
  - "3.6"
  - "3.7-dev"
install:
  - pip install .
  - pip install -r requirements-dev.txt
script:
  - pytest
  - coverage run --source craigslist -m pytest
after_success:
  - coveralls
